# Generated by Django 4.2.1 on 2023-06-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='contact_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
