version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    command: sh docker/production/setup.sh
    container_name: academy-master-backend
    ports:
      - 8000:8000
    volumes:
      - .:/backend
    restart: on-failure
    networks:
      - main
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    depends_on:
      - database

  database:
    image: postgres:12
    container_name: academy-master-postgres
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/posgresql/data
    networks:
      - main
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234EErr
      - POSTGRES_DB=academy_master_production

networks:
  main: