version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: sh docker/local/commands/setup.sh
    container_name: academy-master-backend
    ports:
      - 8000:8000
    volumes:
      - .:/backend
    restart: on-failure
    networks:
      - main
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - database
      - rabbitmq
      - redis
      - smtp4dev

  database:
    image: postgres:12
    container_name: academy-master-postgres
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    networks:
      - main
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234EErr
      - POSTGRES_DB=academy_master_local  

  test_database:
    image: postgres:12
    container_name: academy-master-postgres-test
    restart: on-failure
    ports:
      - 5431:5432
    networks:
      - main
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234EErr
      - POSTGRES_DB=academy_master_local_test

  celery:
    build: 
      context: .
      dockerfile: docker/local/Dockerfile
    container_name: academy-master-celery
    command: sh docker/local/commands/celery.sh 
    depends_on:
      backend:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/backend
    networks:
      - main    
  rabbitmq:
      image: rabbitmq:3.10-management-alpine
      hostname: rabbitmq
      container_name: academy-master-rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        - RABBITMQ_DEFAULT_USER=rabbituser
        - RABBITMQ_DEFAULT_PASS=1234EErr
        - RABBITMQ_DEFAULT_VHOST=/
      networks:
        - main
      healthcheck:
        test: ["CMD", "rabbitmqctl", "status"]
        interval: 3s
        timeout: 3s
        retries: 5

  redis:
    image: redis:6.2-alpine
    container_name: academy-master-redis
    
    ports:
      - 6379:6379
    networks:
      - main
    restart: always

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: academy-master-smtp4dev

    ports:
      - 5000:80
      - 25:25  
    restart: always

networks:
  main:

volumes:
  postgres-data: