# Generated by Django 4.2.1 on 2023-06-10 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='NO address were provided.', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_id',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\+98\\d{10}$')]),
        ),
    ]
