# Generated by Django 4.2.1 on 2023-07-09 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_alter_enrollment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
