# Generated by Django 4.2.1 on 2023-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="token",
            field=models.CharField(default=534, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
