# Generated by Django 4.2.1 on 2023-06-18 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("managers", "0002_manager_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manager",
            options={"verbose_name": "Manager", "verbose_name_plural": "Managers"},
        ),
    ]
