name: Test On Kubernetes
description: "Test the application on kubernetes"

runs:
  using: 'composite'
  steps:
    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'latest'

    - name: Create ConfigMap
      run: kubectl create configmap academy-master-env --from-env-file=./backend/.env.local && kubectl create configmap academy-master-env-file --from-file=.env=./backend/.env.local &&  kubectl create configmap postgres-initdb-script --from-file=./backend/docker/commands/pg-entrypoint.sh
      shell: bash

    - name: Run Kubernetes Deployments
      run: kubectl apply -f kubernetes/
      shell: bash

    - name: Wait for Redis Service
      run: kubectl wait --for=condition=available --timeout=60s deployment/academy-master-redis-dp
      shell: bash

    - name: Wait for Backend Deployments
      run: kubectl wait --for=condition=available --timeout=60s deployment/academy-master-backend-dp
      shell: bash

    - name: Run Backend Tests
      run: kubectl exec -it $(kubectl get pods | grep backend | awk '{print $1}') -- pytest
      shell: bash