# Generated by Django 4.2.1 on 2023-06-07 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_verificationcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verificationcode",
            options={"ordering": ["expire_at"]},
        ),
        migrations.RenameField(
            model_name="verificationcode",
            old_name="created_at",
            new_name="expire_at",
        ),
    ]
