apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-master-backend-dp
  labels:
    app: academy-master-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-master-backend
  template:
    metadata:
      labels:
        app: academy-master-backend
    spec:
      containers:
      - name: backend
        image: mohammadbaj/academy_master:latest
        command: ["/bin/sh"]
        args: [ "/backend/docker/commands/setup.sh" ]

        volumeMounts:
        - name: env-file
          mountPath: /backend/.env
          subPath: .env

        envFrom:
        - configMapRef:
            name: academy-master-env


        ports:
        - containerPort: 8000

        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.local"
        - name: ENVIRONMENT
          value: "LOCAL"
        - name: DATABASE_PORT
          value: "5432"

      volumes:
      - name: env-file
        configMap:
          name: academy-master-env-file
          items:
            - key: .env
              path: .env

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: academy-master-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000


