apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-master-celery-dp
  labels:
    app: academy-master-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-master-celery
  template:
    metadata:
      labels:
        app: academy-master-celery
    spec:
      containers:
      - name: celery-master
        image: ml06py/academy_master:latest
        command: ["/bin/sh"]
        args: [ "/backend/docker/commands/celery.sh" ]

        envFrom:
        - configMapRef:
            name: academy-master-env

        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.local"
        - name: ENVIRONMENT
          value: "LOCAL"


      - name: celery-slave
        image: ml06py/academy_master:latest
        command: ["/bin/sh"]
        args: [ "/backend/docker/commands/celery-beat.sh" ]

        envFrom:
        - configMapRef:
            name: academy-master-env
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.local"
        - name: ENVIRONMENT
          value: "LOCAL"

