apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-master-postgres-dp
  labels:
    app: academy-master-postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-master-postgres

  template:
    metadata:
      labels:
        app: academy-master-postgres
    spec:
      containers:
        - name: postgres

          envFrom:
          - configMapRef:
              name: academy-master-env

          env:
          - name: POSTGRES_USER
            value: "$(DATABASE_USER)"
          - name: POSTGRES_PASSWORD
            value: "$(DATABASE_PASSWORD)"
          - name: POSTGRES_DB
            value: "$(DATABASE_NAME)"
          - name: POSTGRES_MULTIPLE_DATABASES
            value: "$(DATABASE_NAME),$(DATABASE_TEST_NAME)"

          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-vol
          - mountPath: /docker-entrypoint-initdb.d/entrypoint.sh
            name: postgres-initdb

          image: postgres:12
          ports:
          - containerPort: 5432


      volumes:
      - name: postgres-vol
        emptyDir: {}
      - name: postgres-initdb
        configMap:
          name: postgres-initdb

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: academy-master-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
