apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-master-prometheus-dp
  labels:
    app: academy-master-prometheus

spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-master-prometheus

  template:
    metadata:
      labels:
        app: academy-master-prometheus
    spec:
      containers:
        - name: prometheus

          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml

          image: prom/prometheus
          ports:
            - containerPort: 9090

      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: academy-master-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
