apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-master-rabbitmq-dp
  labels:
    app: academy-master-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-master-rabbitmq
  template:
    metadata:
      labels:
        app: academy-master-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.10-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672

        envFrom:
        - configMapRef:
            name: academy-master-env

        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics 
            - check_running
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 3
          failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: academy-master-rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: ui
      protocol: TCP
      port: 15672
      targetPort: 15672
