apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-master-test-postgres-dp
  labels:
    app: academy-master-test-postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-master-test-postgres

  template:
    metadata:
      labels:
        app: academy-master-test-postgres
    spec:
      containers:
        - name: test-postgres

          envFrom:
            - configMapRef:
                name: academy-master-env

          env:
            - name: POSTGRES_USER
              value: "$(TEST_DATABASE_USER)"
            - name: POSTGRES_PASSWORD
              value: "$(TEST_DATABASE_PASSWORD)"
            - name: POSTGRES_DB
              value: "$(TEST_DATABASE_NAME)"

          image: postgres:12
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: test-database
spec:
  selector:
    app: academy-master-test-postgres
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 5432
