# Generated by Django 4.2.1 on 2023-07-04 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_alter_activity_enrollment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together=set(),
        ),
    ]
