# Generated by Django 4.2.1 on 2023-07-04 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0003_alter_course_days"),
        ("activities", "0003_alter_activity_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together={("course", "user")},
        ),
    ]
