# Generated by Django 4.2.1 on 2023-07-09 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0004_alter_activity_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
