name: "Test On Docker"
description: "Test The Code On Docker"

runs:
  using: composite
  steps:
    - name: SetUp Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull The Image
      run: docker pull ${{ inputs.registry }}/${{ inputs.image_name }}:latest

    - name: Run Containers
      run: make run DETACHED=true

    - name: Wait for backend container to prepare
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'

    - name: Run tests
      run: make test
